name: Build and push Docker image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        run: |
          VERSION=$(echo "${{ github.ref_name }}"
          DATE=$(date +%Y%m%d%H%M%S)
          echo "DATE_TAG=${VERSION}-${DATE}" >> $GITHUB_ENV
          echo "TAG=${VERSION}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: cruizba
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Ubuntu 20.04 - Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ubuntu-focal.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: >
            cruizba/ubuntu-dind:focal-${{ env.TAG }},
            cruizba/ubuntu-dind:focal-${{ env.DATE_TAG }}

      - name: Ubuntu 22.04 - Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ubuntu-jammy.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: >
            cruizba/ubuntu-dind:jammy-${{ env.TAG }},
            cruizba/ubuntu-dind:jammy-${{ env.DATE_TAG }}
            cruizba/ubuntu-dind:latest

      - name: Ubuntu 24.04 - Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ubuntu-noble.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: >
            cruizba/ubuntu-dind:noble-${{ env.TAG }},
            cruizba/ubuntu-dind:noble-${{ env.DATE_TAG }}
