name: ci

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image TAG with lower-cased repository name
        run: |
          echo "TAG=ghcr.io/${REPOSITORY,,}:latest" >>${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAG }}
          file: ubuntu-noble.Dockerfile
